sudo: false
language: groovy
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.gradle/caches"
  - "$HOME/.m2"
before_install:
- openssl aes-256-cbc -K $encrypted_f47828c61913_key -iv $encrypted_f47828c61913_iv
  -in secrets.tar.gz.enc -out secrets.tar.gz -d
- tar xzvf secrets.tar.gz
